spring.datasource.url=jdbc:postgresql://${DB_HOST}:5433/gerenciador_Pedidos
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#mostra o que esta sendo feito no banco, o que a JPA está fazendo
#spring.jpa.show-sql=true
#ver tudo formatado no log
#spring.jpa.format-sql=true